//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scribe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scribe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A game built with this system offers many of the features of contemporary quest-driven building games but in a simple, top-down world and without combat..
        /// </summary>
        internal static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information visit:.
        /// </summary>
        internal static string AboutLinkPreamble {
            get {
                return ResourceManager.GetString("AboutLinkPreamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string CaptionAbout {
            get {
                return ResourceManager.GetString("CaptionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Parquet.
        /// </summary>
        internal static string CaptionAccessingParquetError {
            get {
                return ResourceManager.GetString("CaptionAccessingParquetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Scribe.
        /// </summary>
        internal static string CaptionExitWarning {
            get {
                return ResourceManager.GetString("CaptionExitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Create Templates.
        /// </summary>
        internal static string CaptionFolderNotEmptyError {
            get {
                return ResourceManager.GetString("CaptionFolderNotEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string CaptionNewWarning {
            get {
                return ResourceManager.GetString("CaptionNewWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string CaptionReloadWarning {
            get {
                return ResourceManager.GetString("CaptionReloadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string CaptionVersion {
            get {
                return ResourceManager.GetString("CaptionVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error accessing the Parquet library.  Data might be in an inconsistent state.  :(.
        /// </summary>
        internal static string ErrorAccessingParquet {
            get {
                return ResourceManager.GetString("ErrorAccessingParquet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is not empty!
        ///Folder: {1}.
        /// </summary>
        internal static string ErrorFolderNotEmpty {
            get {
                return ResourceManager.GetString("ErrorFolderNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value must be an integer..
        /// </summary>
        internal static string ErrorIntegersOnly {
            get {
                return ResourceManager.GetString("ErrorIntegersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the project folder to load..
        /// </summary>
        internal static string InfoMessageLoad {
            get {
                return ResourceManager.GetString("InfoMessageLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the new project folder..
        /// </summary>
        internal static string InfoMessageNew {
            get {
                return ResourceManager.GetString("InfoMessageNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ParquetIcon {
            get {
                object obj = ResourceManager.GetObject("ParquetIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/mxashlynn/Scribe.
        /// </summary>
        internal static string RepositoryURL {
            get {
                return ResourceManager.GetString("RepositoryURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StrikeRangeDiagram {
            get {
                object obj = ResourceManager.GetObject("StrikeRangeDiagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really quit?  Unsaved changes will be lost!.
        /// </summary>
        internal static string WarningMessageExit {
            get {
                return ResourceManager.GetString("WarningMessageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon unsaved changes and reload data?.
        /// </summary>
        internal static string WarningMessageReload {
            get {
                return ResourceManager.GetString("WarningMessageReload", resourceCulture);
            }
        }
    }
}
