//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scribe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scribe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A game built with this system offers many of the features of contemporary quest-driven building games but in a simple, top-down world and without combat..
        /// </summary>
        internal static string AboutDetails {
            get {
                return ResourceManager.GetString("AboutDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information visit:.
        /// </summary>
        internal static string AboutLinkPreamble {
            get {
                return ResourceManager.GetString("AboutLinkPreamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string CaptionAbout {
            get {
                return ResourceManager.GetString("CaptionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Parquet.
        /// </summary>
        internal static string CaptionAccessingParquetError {
            get {
                return ResourceManager.GetString("CaptionAccessingParquetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Scribe.
        /// </summary>
        internal static string CaptionExitWarning {
            get {
                return ResourceManager.GetString("CaptionExitWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Create Templates.
        /// </summary>
        internal static string CaptionFolderNotEmptyError {
            get {
                return ResourceManager.GetString("CaptionFolderNotEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribe.
        /// </summary>
        internal static string CaptionMainEditorFormClean {
            get {
                return ResourceManager.GetString("CaptionMainEditorFormClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribe *.
        /// </summary>
        internal static string CaptionMainEditorFormDirty {
            get {
                return ResourceManager.GetString("CaptionMainEditorFormDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string CaptionNewWarning {
            get {
                return ResourceManager.GetString("CaptionNewWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string CaptionReloadWarning {
            get {
                return ResourceManager.GetString("CaptionReloadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string CaptionVersion {
            get {
                return ResourceManager.GetString("CaptionVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow.
        /// </summary>
        internal static string CaptionWorkflow {
            get {
                return ResourceManager.GetString("CaptionWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error accessing the Parquet library.  Data might be in an inconsistent state.  :(.
        /// </summary>
        internal static string ErrorAccessingParquet {
            get {
                return ResourceManager.GetString("ErrorAccessingParquet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while accessing Roller: {0}.
        /// </summary>
        internal static string ErrorAccessingRoller {
            get {
                return ResourceManager.GetString("ErrorAccessingRoller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to add an inventory slot.  This likely is a logic error in Scribe or Parquet.  You might want to reload before continuing to work with this inventory.  Sorry about this!.
        /// </summary>
        internal static string ErrorAddingSlot {
            get {
                return ResourceManager.GetString("ErrorAddingSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribe cannot recover and needs to close.  Please save your work and exit..
        /// </summary>
        internal static string ErrorFatal {
            get {
                return ResourceManager.GetString("ErrorFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is not empty!
        ///Folder: {1}.
        /// </summary>
        internal static string ErrorFolderNotEmpty {
            get {
                return ResourceManager.GetString("ErrorFolderNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image editor could not be found at the specified path..
        /// </summary>
        internal static string ErrorImageEditorNotFound {
            get {
                return ResourceManager.GetString("ErrorImageEditorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value must be an integer..
        /// </summary>
        internal static string ErrorIntegersOnly {
            get {
                return ResourceManager.GetString("ErrorIntegersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribe attempted to load a project but encountered an error.  Please check the log..
        /// </summary>
        internal static string ErrorLoadFailed {
            get {
                return ResourceManager.GetString("ErrorLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of this type of model already exists..
        /// </summary>
        internal static string ErrorMaximumIDReached {
            get {
                return ResourceManager.GetString("ErrorMaximumIDReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribe attempted to create a new project but encountered an error.  Please check the log..
        /// </summary>
        internal static string ErrorNewFailed {
            get {
                return ResourceManager.GetString("ErrorNewFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logger was passed null during initialization..
        /// </summary>
        internal static string ErrorNullLogger {
            get {
                return ResourceManager.GetString("ErrorNullLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse saved settings value {0}..
        /// </summary>
        internal static string ErrorParseFailed {
            get {
                return ResourceManager.GetString("ErrorParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value must be an integer greater than 0..
        /// </summary>
        internal static string ErrorPositiveIntegersOnly {
            get {
                return ResourceManager.GetString("ErrorPositiveIntegersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text entered cannot be used.  Parquet reserves the following words: {0}.
        /// </summary>
        internal static string ErrorReservedWord {
            get {
                return ResourceManager.GetString("ErrorReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribe attempted to save the project but encountered an error.  Please check the log..
        /// </summary>
        internal static string ErrorSaveFailed {
            get {
                return ResourceManager.GetString("ErrorSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string FolderNameNewProject {
            get {
                return ResourceManager.GetString("FolderNameNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string FolderNameOldProject {
            get {
                return ResourceManager.GetString("FolderNameOldProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImageNotFoundGraphic {
            get {
                object obj = ResourceManager.GetObject("ImageNotFoundGraphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project Folder.
        /// </summary>
        internal static string InfoMessageLoad {
            get {
                return ResourceManager.GetString("InfoMessageLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project Folder.
        /// </summary>
        internal static string InfoMessageNew {
            get {
                return ResourceManager.GetString("InfoMessageNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string InfoMessageReady {
            get {
                return ResourceManager.GetString("InfoMessageReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ParquetIcon {
            get {
                object obj = ResourceManager.GetObject("ParquetIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/mxashlynn/Scribe.
        /// </summary>
        internal static string RepositoryURL {
            get {
                return ResourceManager.GetString("RepositoryURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StrikeRangeDiagram {
            get {
                object obj = ResourceManager.GetObject("StrikeRangeDiagram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item definitions exist in this project.  Create some using the Items tab!  ^_^.
        /// </summary>
        internal static string WarngingNoItemsExist {
            get {
                return ResourceManager.GetString("WarngingNoItemsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Recent Projects.
        /// </summary>
        internal static string WarngingNoRecentProject {
            get {
                return ResourceManager.GetString("WarngingNoRecentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really quit?  Unsaved changes will be lost!.
        /// </summary>
        internal static string WarningMessageExit {
            get {
                return ResourceManager.GetString("WarningMessageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon unsaved changes and reload data?.
        /// </summary>
        internal static string WarningMessageReload {
            get {
                return ResourceManager.GetString("WarningMessageReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not adding duplicate {0}..
        /// </summary>
        internal static string WarningNotAddingDuplicate {
            get {
                return ResourceManager.GetString("WarningNotAddingDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected to edit..
        /// </summary>
        internal static string WarningNothingSelected {
            get {
                return ResourceManager.GetString("WarningNothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet finished.  Paige will get to it!  ^_^.
        /// </summary>
        internal static string WarningNotImplemented {
            get {
                return ResourceManager.GetString("WarningNotImplemented", resourceCulture);
            }
        }
    }
}
